import { useMemo } from 'react';
import WorkspaceInsightsSidebar from '../components/WorkspaceInsightsSidebar';

type WorkspaceInsightsSidebarProps = React.ComponentProps<typeof WorkspaceInsightsSidebar>;

export function useWorkspaceInsightsSidebarProps({
    currentLanguage,
    provenancePanel,
    provenanceStatusLabel,
    latestWorkflowEntry,
    isGenerating,
    batchProgress,
    resultStatusSummary,
    resultStatusTone,
    currentStageAsset,
    currentStageBranchSummary,
    currentStageSourceTurn,
    currentStageSourceHistoryId,
    activeBranchSummary,
    sessionContinuitySignals,
    conversationSummary,
    conversationSourceTurn,
    sessionSourceTurn,
    branchLabelByTurnId,
    onHistorySelect,
    getStageOriginLabel,
    getLineageActionLabel,
    getLineageActionDescription,
    getShortTurnId,
    getBranchAccentClassName,
    renderHistoryTurnSnapshotContent,
    renderHistoryTurnBadges,
    renderHistoryTurnActionRow,
}: WorkspaceInsightsSidebarProps) {
    return useMemo(
        () => ({
            currentLanguage,
            provenancePanel,
            provenanceStatusLabel,
            latestWorkflowEntry,
            isGenerating,
            batchProgress,
            resultStatusSummary,
            resultStatusTone,
            currentStageAsset,
            currentStageBranchSummary,
            currentStageSourceTurn,
            currentStageSourceHistoryId,
            activeBranchSummary,
            sessionContinuitySignals,
            conversationSummary,
            conversationSourceTurn,
            sessionSourceTurn,
            branchLabelByTurnId,
            onHistorySelect,
            getStageOriginLabel,
            getLineageActionLabel,
            getLineageActionDescription,
            getShortTurnId,
            getBranchAccentClassName,
            renderHistoryTurnSnapshotContent,
            renderHistoryTurnBadges,
            renderHistoryTurnActionRow,
        }),
        [
            currentLanguage,
            provenancePanel,
            provenanceStatusLabel,
            latestWorkflowEntry,
            isGenerating,
            batchProgress,
            resultStatusSummary,
            resultStatusTone,
            currentStageAsset,
            currentStageBranchSummary,
            currentStageSourceTurn,
            currentStageSourceHistoryId,
            activeBranchSummary,
            sessionContinuitySignals,
            conversationSummary,
            conversationSourceTurn,
            sessionSourceTurn,
            branchLabelByTurnId,
            onHistorySelect,
            getStageOriginLabel,
            getLineageActionLabel,
            getLineageActionDescription,
            getShortTurnId,
            getBranchAccentClassName,
            renderHistoryTurnSnapshotContent,
            renderHistoryTurnBadges,
            renderHistoryTurnActionRow,
        ],
    );
}
